### PR TITLE
Added some basic testing to User implementation (WIP).

### PR DESCRIPTION
**Pull request by duberlyguarnizofuentesrivera**
Added Mockito as dependency.
Modified update() method in UserServiceImp.java to copy one missing parameter.

### CODE REVIEW

**Comment by JEstebanCDev** [comment]
Thanks man, If you want to know more about the project I'll leave my postman to test 

https://documenter.getpostman.com/view/13987920/UzBiQoon

**Comment by duberlyguarnizofuentesrivera** [comment]
> I got problems to deploy the last commit, so I just commented all the FastFoodAppApplicationTests.java

Hi! Mind to post screenshot of the error, please? I want to continue testing all other services. In other hand, what do you mean with this?

> I had the same error before

**Comment by JEstebanCDev** [comment]
Error

That's the error but I didn't found how to solve it, I know that the error isn't in that especifications the error is cause for other reason 100% sure.

**Comment by JEstebanCDev** [comment]
Now is deploy but only comment the FastFoodAppApplicationTests.java
On the other hand only the AppUserRole.ROLE_ADMIN can update the Roles 

And in that endpoint in the frontend I only show customers so it is not necessary to update the role, the role is always ROLE_CLIENT.
I will create another service to update employees or new administrators, So in that case ,yes, you might update the roles

image

**Comment by duberlyguarnizofuentesrivera** [comment]
I Just fixed it, it was a POM related issue and a missing plugin.

**Pull request merged**
